name: Commitlint
'on':
  workflow_call: null
permissions:
  contents: read
  pull-requests: read
jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check commit messages
      uses: wagoid/commitlint-github-action@v6
